apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-royx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0011-tenant/tkrw-pr714-0075-0011-app/devfile-sample-royx@sha256:139eee87af775a3692cce9fb349d6b5e8fd0174c9fdf913f0bdb623aeb6e4f1b
        name: my-nodejs
        resources: {}
status: {}
